const beers = {};


beers.all = [
  'Cantillon St Lamvinus Grand Cru',
  'Cantillon Vigenronne',
  'Cantillon Rose de Grambrinus',
  'Tilquin Gueuze',
  'Tilquin Quetsche',
  'Boon Still Lambic',
  'Oxbow Spaced Aged Barrel Boy',
  'Oxbow Metal face',
  'Oxbow Cavern',
  'Oxbow Sarcophagus',
  'Oxbow Luppolo',
  'Oxbow Synthesis',
  'Oxbow Sasiontino',
  'Oxbow Infinite Darkness',
  'Stillwater Oude Bae',
  'Stilwlater Gnam Gnam',
  'Stillwater Hopvine Bling',
  'Stillwater/Pohjala- Here Comes The Night',
  'Stillwater Tangerine haze',
  'Stillwater Stateside',
  'Stillwater Cellar Door',
  'Oxbow Double Daisy farmer',
  'Oxbow Native/Wild',
  'Oxbow Nocturnality',
  'Oxbow Punch Book',
  'Stillwater/Friegiest- Amis',
  'Stillwater/Toccalamatto- Armella',
  'Perennial Abraxas',
  'Perennial Vanilla Abraxas',
  'Perennial Coffee Abraxas',
  'Perennial Citra Paradisi',
  'Perennial/Jester King-Til the Night',
  'Pereniial Edgewild Saison',
  'Perennial Pilsner',
  'Perennial Foeder Saison',
  'Perennial Owen',
  'Perennial Meriwether',
  'Allagash James & Julie',
  'Allagash Pastiche',
  'Allagash lil Sal',
  'Allagash Interlude 2016',
  'Allagash Interlude 2017',
  'Allagash White',
  'Allagash Emile',
  'Allagash Ciruex',
  'Allagash Map 40',
  'Allagash Hibernal Fluxus 2017 ',
  'Allagash Hive 56 2016',
  'Allagash Hive 56 2017',
  'Allagash 16 Counties',
  'Allagash Century',
  'Perennial Funky Wit',
  'Perennial Foeder Saison',
  'Perennial Mint 17',
  'Blackberry farms Super Saison',
  'Blackberry farms Classic',
  'Blackberry farms Hoppy Wheat',
  'Blackberry farms Steps to Nowhere',
  'Cantillon Kriek ',
  'Blackberry farms Brett Saison 18 2017',
  'Blackberry farms Flanders 2017',
  'Blackberry farms Brett Saison 2016',
  'Blackberry farms Brett Saison 2017',
  'Blackberry farms Triple 2016',
  'Blackberry farms Brett Fruited Blend 2017',
  'Blackberry farms Wild Classic',
  'Blackberry farms/Stillwater Sensibility',
  'Blackberry farms Blackberry Rye',
  'Blackberry farms Noble Cuvee Dry Hopped Saison',
  'Blackberry farms Peel Your face',
  'Crooked Stave Surette Reserve raspberry',
  'Crooked Stave Surette Reserve Blueberry',
  'Crooked Stave L’Brett O’Blueberry',
  'Crooked Stave L’Brett D’Sour Cherry',
  'Crooked Stave Petite Sour Merionberry',
  'Cantillon Gueuze',
  '3 Fonteinen Armand & Gaston',
  'Achouffe La Chouffe',
  'Abbaye De Rocs Brune',
  'Abbaye De Rocs Grand Cru',
  'Alvinne Berliner Framboos Weisse',
  'Alvinne Cuvee De Mortagne',
  'Alvinne Cuvee Freddy',
  'Alvinne Gentleman’s Sour',
  'Alvinne Kriek De Mortagne',
  'Alvinne Kweeper',
  'Alvinne Omega',
  'Alvinne Sour’ire De Mortagne',
  'Alvinne Wild West Cherry & Raspberry',
  'Alvinne Wild West French Plum',
  'Alvinne Wild West Primitivo Grapes',
  'Bastogne Ardenne Saison',
  'Bastogne Ardenne Stout',
  'Blaugies Saison Epeature',
  'Blaugies/Hill Farmstead- Le Vermontoise',
  'BOM Bling Bling',
  'BOM Wild & Funky',
  'Boon Lambic',
  'Brugse Zot Blonde',
  'Cantillon Kriek',
  'Cantillon Rose De Grambrinus',
  'Cantillon St Lamvinus Grand Cru',
  'Cantillon Vignerionne',
  'Cantillon Gueuze',
  'Chimay Blue',
  'Chimay White',
  'Chimay Red',
  'De Brabandere Me’Lange',
  'De Brabandere Petrus 40/40/20',
  'De Brabandere Petrus 80/20',
  'De Brabandere Petrus Quad Nitro',
  'De Brabandere Petrus Sour Apricot',
  'De Brabandere Sour Mango',
  'De Brabandere Petrus Sour Quad',
  'De Dolle Dulle Teve',
  'De Dolle Special Export Stout',
  'De Dolle Stille nacht',
  'De Glazen Toren Canaster',
  'De Glazen Toren Jan De Lichte',
  'De Glazen Toren Saison De Epre mere',
  'De La Senne Jambe De Bois',
  'De La Senne Taras Boulba',
  'De La Senne Zinnebier',
  'De Leite Cuvee Mam’Selle',
  'De Leite Cuvee Soeur’ise',
  'De Leite Fils A Papa V',
  'De Leite Ma Mere Speciale',
  'De Meester Dubbel',
  'De Meester Quadrupel',
  'De Proef/New Glarus Abtsolution',
  'De Ranke Hop Harvest',
  'De Ranke Pere Noel',
  'De Ranke Simplex',
  'Den Hopperd Kameleon Saison Bio',
  'Den Hopperd Kameleon Special Tripel Bio',
  'Drie Fonteinen Beersel Blonde',
  'Drie Fonteinen Beersel Lager',
  'Dupont Saison',
  'Duvel Single',
  'Fantome Pissenlit',
  'Fantome Saison',
  'Hanssens Oudbeitje',
  'Hanssens Experimental Cassis',
  'Hanssens Oude Lambic',
  'Het Anker Gouden Carolus Ambrio',
  'Het Anker Gouden Carolus Classic',
  'Het Anker Lucifer',
  'Het Anker Lucifer Black',
  'Het Nest BA Dead Mans Hand (Cognac)',
  'Het Nest BA Dead Mans Hand (Whiskey)',
  'Het Nest Schuppenbier Grand Cru (Cognac)',
  'Huyghe Delirium Tremens',
  'Huyghe Delirium Guillotine',
  'Hof Ten Dormaal Dads Tea',
  'Kerkom Adelardus Dubbel',
  'Kerkom Adelardus Tripel',
  'Kerkom Bink Bloesem',
  'Kerlom Bink Blonde',
  'Kerkom Bink Bruin',
  'La Rulles Brune',
  'La Rulles Cuvee Meilleurs Vouex',
  'La Rulles Estivale',
  'La Rulles Grand 10',
  'La Rulles Triple',
  'Oud Beersel Bersalis Sour Blend',
  'Oud Beersel Still Lambic',
  'Prearis BA Grand Cru',
  'Rodenbach Alexander',
  'Rodenbach Foederbier',
  'Rodenbach Vintage 2015',
  'Silly Barrel aged Scotch De Silly',
  'Slaapmutske Flemish Old Style',
  'Slaapmurtske Triple Night Cap',
  'St Bernardus Abt 12',
  'St Bernardus Wit',
  'St Bernardus Baksteen Winkel',
  'St Bernardus Prior 8',
  'St Bernardus Tripel',
  'St Feulillen Saison',
  'St Louis Gueuze Fond Tradition',
  'St Louis Gueuze Fond Tradition Kriek',
  'Straffe Hendrick Heritage 2013 Cognac',
  'Straffe Hendrick Heritage 2014 Brandy',
  'Tilquin Gueuze',
  'Tilquin Questche',
  'Tilquin Rullquin',
  'Troubadour Magma Hop Twist',
  'Val Dieu Blonde',
  'Val Dieu Brune',
  'Van Eecke Kapittel Blonde',
  'Van Honsebrouck Kasteel Raspberry Bartista',
  'Van Honsebrouck Kasteel Rouge',
  'Van Honsebrouck Kasteel Triple',
  'Van Steenberge Blonde',
  'Van Steenberge Ertvelds Wit',
  'Van Steenberge Gulden Draak Calavados',
  'Van Steenberge Gulden Draak Nitro',
  'Van Steenberge Monks Cafe Grand Cru',
  'Van Steenberge Piraat',
  'Verhaeghe Barbe Ruby',
  'Verhaeghe Duchesse De Bourgogne',
  'Verzet Oud Bruin Vineyard',
  'Verzet Golden Tricky',
  'Verzet Moose Blues',
  'Verzet Oud Bruin Cherry',
  'Verzet Oud Bruin Oak Leaf',
  'Verzet Super Noah',
  'Viven IPA',
  'Wittekerke Wit ',
  'Anchorage The Ghosts in their Eyes',
  'Anchorage Easy Evil',
  'Arcadia 21st Anniversary',
  'Bells Wild One',
  'Brooklyn Bel Air',
  'Brewers Art Charb',
  'Bullfrog Le Roar Grrrz Kriek',
  'Bullfrog Le Roar Cocoa Framboise',
  'Bullfrog Jong Bruin Kriek',
  'Burley Oak Blackberry Mango JREAM',
  'Burley Oak Blueberry Cobbler JREAM',
  'Burley oak Double Berry Cherry JREAM',
  'Burley oak Grape Quish Cabernet',
  'Burley oak Grape Quish Chardonnay',
  'Burley Oak Level',
  'Burley oak Tangerine Cherry JREAM',
  'Captain Lawrence Rosso Marron',
  'Captain Lawrence Viola',
  'Cascade Bourbonic Plague',
  'Cascade Midnight Bramble',
  'Council Broken Wand Boysenberry',
  'Council Woofle Dust Apricot',
  'Council/Modern Times-Modern Magic',
  'Epic Oak & Orchard Pinot',
  'Epic Oak & Orchard Syrah',
  'Fegleys Gueuze',
  'Firestone Walker Bretta Weisse 2016',
  'Firestone Walker Krieky Bones',
  'Free Will Saison Rose',
  'Free Will Whit',
  'Grimm Cherry raspberry Pop',
  'Grimm Galaxy Pop',
  'Grimm Pychokinesis',
  'Grimm Rainbow Dome',
  'Highway Manor Funky Prowler',
  'Highway Manor Mr Strawberry',
  'Highway Manor Mr Tea',
  'Jester King Nocturn Chysalis',
  'Jester King Viking Metal',
  'Lost Rhino Exesus Sanctum Peach Sour',
  'Manor Hill Oud Bruin w/ Figs',
  'Monument City –TBA',
  'New Belgium Felix Apple Whiskey $33',
  'New Belgium Oscar Blackberry Whiskey $17',
  'New Belgium Single Foeder Felix #61',
  'New Belgium Single Foeder Oscar #1',
  'New Belgium Oscar Worthy Coffee (Nitro)',
  'OEC Pasca 2016',
  'OEC Vetus',
  'OEC Vindemia Blanc',
  'OEC Brunneis',
  'OEC Clavis Purpura',
  'OEC Stramboolzed',
  'Prairie Vous Francais',
  'The Bruery Terreaux Train to Beersel',
  'The Bruery Terreaux Melange #9',
  'The Bruery Terreaux/Jester King-Bouffon',
  'The Bruery Terreaux Filmishmish',
  'The Bruery Terreaux Summa Vitis',
  'Union Older Pro Apricot',
  'Union Older Pro Gin BA',
  'Union Older Pro Red raspberry',
  'Union BA Midnight Maurder ',
  'Anchorage/Jolly Pumpkin-Matame Aherta',
  'Avery Certatio Equestris 2016',
  'Avery Lunctis Viribus 2016',
  'Bullfrog Le Roar Grrrz Arandei',
  'Bullfrog Le Roar Grrrz Blackberry',
  'Bullfrog Le Roar Grrrz Blueberry',
  'Bullfrog Le Roar Framboise',
  'Bullfrog Oud Bruin',
  'Bullfrog Rood Bruin Kriek',
  'Captain Lawrence Hops & Roses',
  'Cascade Vitis Noble',
  'Cascade/The Bruery One Way or Another',
  'Council Behind The Curtain',
  'Council Vienne',
  'Epic/The Commons-Common Interests',
  'Draai Laag Black Briar',
  'Draai Laag Razmata',
  'Draai Laag Red Brair',
  'Firestone Walker Sour Opal',
  'Epic Brainless on Pineapple',
  'Grassroots Artic Soiree',
  'Green Bench Parallax',
  'Green Bench/Brewski-Tiki Tack',
  'Grimm Cherry Pop',
  'Grimm Apricot Pop',
  'Grimm Passionfruit Pop',
  'Grimm Sunshine Pop',
  'Grimm Super Spruce',
  'Highway Manor Mr Blueberry',
  'Jester King Das Wunderkind',
  'Jester King Figlet',
  'Jester King No Whalez Here',
  'Jester King Buddha Brew',
  'Jester King Simple Means',
  'Jester King Mad Meg',
  'Jolly Pumpkin la Vida Improvisacion',
  'Jolly Pumpkin/Monkish Apocolocynposis',
  'Jolly Pumpkin/Anchorage No Ka Ol',
  'Libertine Board room #3',
  'Libertine Framboise',
  'Libertine Heard it through the Grapevine',
  'Libertine Under My Plum',
  'Libertine Pepe Le Pluot',
  'New Belgium Geisha Grand Reserve',
  'Prairie 4th Anniversary',
  'Prairie Brett C',
  'Prairie Apricot funk',
  'Right Proper Astral Weeks',
  'The Bruery Terreux Frucht: Raspberry',
  'The Bruery Terreux/Garage Project-Ngongo',
  'Victory Wisdom Hour ',
  'Cascade Sang Rouge',
  'Cascade Noyaux',
  'Cascade Strawberry',
  'Cascade The Vibne',
  'Cascade Kriek',
  'Cascade Sang Noir',
  'Cascade Figaro',
  'Cascade Elderberry',
  'Cascade Crazy navel',
  'Cascade Tangerine Dream',
  'Cascade Sang Du Chene'
]


  module.exports = beers;