const beers = {};


beers.all = [
"Funky Buddha Maple Bacon Coffee Porter",
"Funky Buddha Free Range Kopi Luwak Maple Bacon Coffee Porter Variant",
"Funky Buddha Jamaican Blue Mountain Maple Bacon Coffee Porter Variant",
"Funky Buddha Louisville Bourbon Barrel-Aged Morning Wood Variant",
"Funky Buddha High West Barrel-Aged Mint Julep",
"Funky Buddha Bourbon Barrel-Aged Old Fashioned",
"Funky Buddha Last Buffalo in the Park",
"Funky Buddha Saint Toddy",
"Funky Buddha Rum Barrel-Aged Batida",
"Funky Buddha Rum Barrel-Aged El Jefe's Coquito",
"Funky Buddha Rum Barrel-Aged Pina Colada",
"Funky Buddha Chardonnay Barrel-Aged Dreamers of Dreams",
"Funky Buddha Chardonnay Barrel-Aged Undefeated Saison",
"Funky Buddha Chardonnay Barrel-Aged Tripel Lindy",
"Funky Buddha Tequila & Rum Barrel-Aged Black Goblin",
"Funky Buddha Indian Moonson Malabar Nikolai Vorlauf",
"Funky Buddha Jamaican Blue Mountain Snowed In",
"Funky Buddha I’m So Excited, I’m So Scared",
"Funky Buddha Chocwork Orange",
"Funky Buddha Wide Awake It’s Morning",
"Funky Buddha Nib Smuggler",
"Funky Buddha Last Snow",
"Funky Buddha French Toast",
"Funky Buddha Save Some Room For Later",
"Funky Buddha Sweet Potato Casserole",
"Funky Buddha No Crusts",
"Funky Buddha Fire in the Hole",
"Funky Buddha Cosmic Journey",
"Funky Buddha Grapefruit Miami Miracle Double Lateral IPA",
"Funky Buddha Miami Miracle Double Lateral IPA",
"Funky Buddha Melon Ballin’",
"Funky Buddha Day Walker",
"Funky Buddha Raspberry Floridian",
"Funky Buddha Sticky Treats",
"Funky Buddha Sticky Nuts",
"Funky Buddha Dragon Fruit Berliner",
"Funky Buddha Key Lime Pie",
"Funky Buddha Core",
"Funky Buddha Floridian",
"Funky Buddha Hop Gun",
"Funky Buddha Crusher",
"Funky Buddha Eternal Summer",
"Funky Buddha Pineapple Beach",
"Funky Buddha Tripel Lindy",
"Funky Buddha Vibin",
"Funky Buddha Hazy Daze",
"Funky Buddha El Camino",
"Funky Buddha Gloves Off",
]


  module.exports = beers;