const beers = {};


beers.all = [
  // "1623 Brewing IPA",
  // "1623 Brewing Pilsner",
  // "1623 Brewing Hazy IPA",
  // "1623 Brewing Hefeweizen",
  // "1812 Brewery	Fagan's Strawberry Wheat",
  // "1812 Brewery	Cumberland Blues Pale Ale",
  // "7 Locks Brewing Shattered Glass ",
  // "7 Locks Brewing Surrender Dorothy ",
  // "Barley & Hops	DIPA Thing",
  // "Barley & Hops	MD Killzner",
  // "Barley & Hops	Ol' Brown-Eye",
  // "Barley & Hops	Smarmelade",
  // "Barley & Hops Spiral Ham",
  // "Brewer's Alley	Kolsch",
  // "Brewer's Alley	IPA",
  // "Brewer's Alley	1634 Ale",
  // "Brewer's Alley	Brickhouse",
  // "Brewer's Alley	Maibock",
  // "Brewer's Alley	Barrel Aged",
  // "Brewery Fire	Travel Expenses",
  // "Brewery Fire	Neon Tuxedo",
  // "Brewery Fire	Rochelle, Rochelle",
  // "Brewery Fire	Speaker for the Red",
  // "Brewery Fire	That's No Moon",
  // "Brookeville Beer Farm	Yellow Finch",
  // "Brookeville Beer Farm	Southern Exposure",
  // "Brookeville Beer Farm	Interdependence",
  // "Bull and Goat Brewery	670",
  // "Bull and Goat Brewery	Frank",
  // "Bull and Goat Brewery	Queen Anne's Revenge",
  // "Calvert Brewing Company	7th State",
  // "Calvert Brewing Company	Playground Legend",
  // "Charm City Meadworks	Elderberry Draft Mead",
  // "Charm City Meadworks	Mango Comapeño",
  // "Charm City Meadworks	Ruby Red Rose",
  // "Checkerspot Brewing	Cask",
  // "Checkerspot Brewing	First Whisper ESB",
  // "Checkerspot Brewing	Locally Delicious",
  // "Checkerspot Brewing	Stomping Ground",
  // "Crooked Crab Brewing	Excessive Juice",
  // "Crooked Crab Brewing	A Boysenberry & Blueberry Walked Into A Bar",
  // "Crooked Crab Brewing	Fairwinds Chocolate Cupcake Porter",
  // "Crooked Crab Brewing	High Joltage",
  // "Cushwa Brewing	Silent Freeways",
  // "Cushwa Brewing	TyPA Workflow Disruption",
  // "Cushwa Brewing	Tenuous Pawn",
  // "Distillery Lane Ciderworks	GalaxCider",
  // "Distillery Lane Ciderworks	Rio Hard Cider",
  // "Distillery Lane Ciderworks	Spring Blossom Hard Cider",
  // "Elder Pine Brewing and Blending	Tropic Chaser",
  // "Elder Pine Brewing and Blending	Treemeister",
  // "Elder Pine Brewing and Blending	Call of the Void",
  // "Elder Pine Brewing and Blending	Pliable Foe",
  // "Evolution Brewing Brut IPA",
  // "Evolution Brewing Day Crush Kettle Sour",
  // "Evolution Brewing Lot 3",
  // "Evolution Brewing Stalker Hefeweizen",
  // "Flying Dog Brewery 2018 Barrel Aged Gonzo",
  // "Flying Dog Brewery Dead Rise Gose",
  // "Flying Dog Brewery Mango Sour",
  // "Flying Dog Brewery Numero Dos",
  // "Flying Dog Brewery Raspberry Sour",
  // "Flying Dog Brewery Tenacious V",
  // "Flying Dog Brewery Thunderpeel",
  // "Full Tilt Brewing	Funk the Tilt",
  // "Full Tilt Brewing	Govans Blood Orange Gose",
  // "Full Tilt Brewing	Hops the Cat",
  // "Full Tilt Brewing	The Beginning, The End",
  // "Guinness Open Gate Brewery	TBD",
  // "Heavy Seas Beer	Citra Cannon",
  // "Heavy Seas Beer	Loose Cannon",

  "Heavy Seas Beer	Smooth Sail",
  "Heavy Seas Beer	TropiCannon",
  "Homaide Brewing Co.A Little Stitious",
  "Homaide Brewing Co.Honey Bunches of Beer",
  "Hysteria Brewing	Monasterium",
  "Hysteria Brewing	Morning After",
  "Hysteria Brewing	New Scoot Juicin'",
  "Hysteria Brewing	Nuffer Flutter",
  "Hysteria Brewing	Seas the Bay",
  "Hysteria Brewing	Tipping Point",
  "Hysteria Brewing	What You Want",
  "Hysteria Brewing	Woke",
  "Hysteria Brewing	Mother's Milk Tiramisu ",
  "Jailbreak Brewing Company	Feed the Monkey",
  "Jailbreak Brewing Company	PC - Funk",
  "Jailbreak Brewing Company	Special Lady Friend",
  "Manor Hill	Chasing Your Own Tail",
  "Manor Hill	Citra Splendor DIPA",
  "Manor Hill	Jousting Windmills: Naranjilla & Pineapple",
  "Manor Hill	Jousting Windmills: Tart Cherry, Sweet Cherry & Red Raspberry",
  "Monocacy Brewing Company	Riot Rye Pale Ale",
  "Monocacy Brewing Company	H.L.Rex Session Pale Ale",
  "Monocacy Brewing Company	Brewtus",
  "Monocacy Brewing Company	Gose of Althes",
  "Monocacy Brewing Company	Blackbird Singing",
  "Oliver Brewing Co	Forearm Smash",
  "Oliver Brewing Co	Sour Cherry Blossom Cask",
  "Oliver Brewing Co	I Wish I Was In Mexico",
  "Prospect Point Brewing	Hopyard Haze",
  "Prospect Point Brewing	YFB",
  "Red Shedman	Andromeda Galaxy",
  "Red Shedman	Blueberry Cider",
  "Red Shedman	Old Scottish Redneck",
  "Red Shedman	Lemon Drop Single Hop Pale",
  "Ruhlman Brewery LLC	Amber Ale",
  "Ruhlman Brewery LLC	Blackstrap Porter",
  "Ruhlman Brewery LLC	MR IPA",
  "Ruhlman Brewery LLC	Red Ale",
  "Steinhardt Brewing	Four Horsemen",
  "Steinhardt Brewing	Kriek",
  "Steinhardt Brewing	Orange Haze",
  "Steinhardt Brewing	Three Wise Men",
  "True Respite Brewing Company	Zulu Alpha",
  "True Respite Brewing Company	Flight of the Falconer",
  "True Respite Brewing Company	Fojito",
  "True Respite Brewing Company	Peach's Parasol",
  "True Respite Brewing Company	Peeled: The Dawn Wall",
  "True Respite Brewing Company	The Plunge",
  "UNION Craft Brewing	Mountain Girl",
  "UNION Craft Brewing	Divine",
  "UNION Craft Brewing	Duckpin",
  "UNION Craft Brewing	Skipjack",
  "UNION Craft Brewing	Rough Draughts: Green Ghost",
  "UNION Craft Brewing	Pink Flamingo",
  "UNION Craft Brewing	Older Pro Black Currant",
  "Waredaca Brewing Co.Zydeco w / Sweet Cherry and Cocoa",
  "Waredaca Brewing Co.Winslow",
  "Waredaca Brewing Co.	321 Gose w / Ginger, Lemon",
  "Olde Mother	Impressionist",
  "Olde Mother	Solana",
  "Olde Mother	Aurora Rose'",
  "Nepenthe Brewing Co.Dubbabeebweepa",
  "Nepenthe Brewing Co.Lord Bones",
  "Nepenthe Brewing Co.Polydribbles",
  "Monument City Brewing Company	51 Rye w / Grapefruit & Peppercorn",
  "Monument City Brewing	Day Hike",
  "Monument City Brewing Company	Gose w / Lime & Lemon",
  "Monument City Brewing Company	The Gusto",
  "Streetcar 82 Brewing Co.Livin' the Hy'Life",
  "Streetcar 82 Brewing Co.Spring Fling",
  "Streetcar 82 Brewing Co.Fancy Nancy",
  "Backshore Brewing Company	Bandwagon",
  "Backshore Brewing Company	Downtown Sugar Brown",
  "Backshore Brewing Company	Boardwalk Blonde"
]


  module.exports = beers;